output: .
lame: lame
sox: sox
flac: flac
metaflac: metaflac
mkvmerge: mkvmerge
# Overrides for particular system types
Windows:
    lame: tools\standalone\lame.exe
    sox: tools\standalone\sox\sox.exe
    flac: tools\standalone\flac.exe
    metaflac: tools\standalone\metaflac.exe
    mkvmerge: tools\standalone\mkvmerge.exe
# Specify particular overrides for each system
# If a system has multiple OSes, common changes
# can go at the level of the machine while
# OS dependent changes go underneath a key
# with the value returned by platform.system()
# Note the system name is returned by
#   socket.gethostname()
#
# Overrides for particular systems
Asusi7:
    Linux:
        output: /storage/Music (MKA)
    Windows:
        output: D:\Music (MKA)
COREQUAD:
    #output: E:\Internet Downloads\Music (MKA)
    output: G:\
